# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# 파일이 실행됐을 때 이름
name: 뉴스속보수집
# on
# 어떤 조건일 때 파일을 실행 시킬지
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
# 실제 파일들을 실행했을 때 어떤 작업들을 할건
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    # pip 최신
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    # 필요한 라이브러리들을 설치하기   
    - name: library install
      run: |
        pip install requests
        pip install beautifulsoup4
        pip install pandas
        pip install lxml
        
    # 내가 만든 파이썬 파일을 실행
    - name: run my file
      run: |
        python3 news.py
        
    # 커밋
    - name: commit
      run: |
        git config --global user.email "tntnto928@naver.com" # 사용하는 이메
        git config --global user.name "M1nse0-Kim" # 이름
        git add data.csv # 가상환경이 아닌 내가 보고 있는 공간에 파일 저장 가능
        git commit -m "뉴스데이터 수집"
    
    # 푸쉬 
    - name: push
      uses: ad-m/github-push-action@master
      with: 
        branch : "main"
        github_token : $
